### PR TITLE
Adding more specific node and npm requirements

### PR DESCRIPTION
**Pull request by mlunoe**
The build and running tests was failing for me using node `4.4.x` and npm `2.15.x`. Specifying requirements should help others not end up in the same situation.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by kennyt** [comment]
conflicts

**Comment by jfurrow** [comment]
@mlunoe Ping!

**Comment by mlunoe** [comment]
This PR doesn't make sense. I think my `node` version was out of sync in one of my terminal tabs and therefore caused issues. I don't experience these issues anymore.

**Pull request closed without merging**
