### PR TITLE
Add beta release instructions

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by daiyiwhale** [comment]
:party-parot:

**Comment by MatApple** [comment]
Thanks @jfurrow! 👍

**Comment by mesosphere-web** [comment]
Reviewer: @rcorral

**Comment by mlunoe** [comment]
How does this relate to what was done here? https://github.com/mesosphere/reactjs-components/pull/302

**Comment by jfurrow** [comment]
@mlunoe Shall I submit another PR instructing users to use those scripts?

**Comment by MatApple** [comment]
That'd be great please John :)

**Pull request merged**
