### PR TITLE
[CNVS Upgrade] Fix stylelint warnings

### PR DESCRIPTION
**Pull request by jfurrow**
This PR formats all of our LESS files to adhere to the new Stylelint rules. It also removes a few unused styles that I discovered.

The actual rules will be introduced in another PR.

### CODE REVIEW

**Comment by MatApple** [comment]
flicts @jfurrow

**Comment by jfurrow** [comment]
Flicts fixed! @MatApple

**Comment by MatApple** [comment]
Got some more @jfurrow :)

**Comment by jfurrow** [comment]
Haha thanks @MatApple should be good now!

**Comment by MatApple** [comment]
@jfurrow - thats a lot of house cleaning, just want to make sure we're intentionally cleaning out ~2000 LOC?

**Comment by mlunoe** [comment]
Those are mainly the files that were not being used, which it states in the description.

**Comment by jfurrow** [comment]
Yep, it is intentional — I also removed a few unused stylesheets that were missed when the docs got updated. I can move those to a separate PR if you'd like!

**Comment by MatApple** [comment]
@jfurrow @mlunoe - thanks, I did read the description and it states "a few" ;) just wanted to make sure since it's a lot of code.

**Pull request merged**
