### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by rcorral**
Updates `browser-sync` and all `eslint` deps.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by mlunoe** [comment]
Needs a rebase

**Comment by rcorral** [comment]
Rebased.

**Comment by rcorral** [comment]
I don't code a lot....but when I do, I add a shit ton of lines.

**Comment by daiyiwhale** [comment]
:+1:

**Pull request merged**
