### PR TITLE
Allow react 15.0.0 and 15.4.0

### PR DESCRIPTION
**Pull request by nLight**
~~ℹ️  it also contains code from #389 and #388~~ Merged!

I did `npm run livereload` and all widgets seemed to be working

### CODE REVIEW

**Comment by nLight** [comment]
Tests pass locally, interesting

**Comment by mlunoe** [comment]
Here are some specifics about the Semver versions: https://docs.npmjs.com/misc/semver

In general, we should use fixed versions for actual dependencies (normal and dev) except for the ones we require as peer dependencies. Here I guess to goal is to be as relaxed to as possible.

I tend to use `x`s when specifying versions as it is more obvious what is happening than when using `~` or `^`.

I just did a test and it will install the highest version possible when using `||` and `x`s (which is also what I remember, but couldn't find any resources for this, though I didn't do a thorough search for it).

**Comment by mlunoe** [comment]
Also, it seems that we are not ready for react 15.x.x

**Comment by nLight** [comment]
Fair points, thanks for the feedback! I'll continue working on the branch.

**Comment by nLight** [comment]
on the other hand we could just roll with 0.14 and 15.4.x :)

**Comment by mlunoe** [comment]
If we do support multiple versions, we should make sure to support the full range.
I would pretty annoyed as a developer that if a library would skip a version (which could happen to be the one I am using).

**Comment by nLight** [comment]
Hey @mlunoe I believe there was an artifact that broke 15.0 build for you. I added all the versions in travis and it is all green 💚

**Comment by nLight** [comment]
though 15.4.x throws some warnings we will eventually address.

**Comment by mlunoe** [comment]
Great! And thank you for cleaning up the package.json! Looks so much better now!

**Pull request merged**
