### PR TITLE
Collapsible proptype blocks

### PR DESCRIPTION
**Pull request by rcorral**
gif

Looking for feedback on looks of this. 
ping: @jfurrow

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by jfurrow** [comment]
I love the idea of the collapsable blocks! What do you think about making the actual example JSX collapsed, too? That would be really helpful to let people see the actual components easily. This is a pain point for me when I'm working on developing a new component.

Regarding the gradient, I think it might look nicer if the gradient were "inside" the container, like so:

**Comment by mlunoe** [comment]
Nice suggestion @jfurrow.
This is cool @rcorral!

**Comment by rcorral** [comment]
Applied updated gradients
img

**Comment by jfurrow** [comment]
@rcorral I pushed two commits, feel free to merge if you're cool with them!

**Pull request merged**
