### PR TITLE
Fix missing @neutral color variable

### PR DESCRIPTION
**Pull request by nLight**
It has been replaced with @grey-dark in CNVS

This PR fixes our `npm run dist` and fixes docs build.

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Comment by ashenden** [comment]
@nLight @MatApple @orlandohohmeier keep in mind this fix, plus several others are address in this branch -- https://github.com/mesosphere/reactjs-components/tree/ashenden/DCOS_OSS-1779-ui-kit-consistency

**Comment by nLight** [comment]
@ashenden thanks for the heads up!

**Comment by nLight** [comment]
Hey @ashenden, I don't see how it is fixed on https://github.com/mesosphere/reactjs-components/tree/ashenden/DCOS_OSS-1779-ui-kit-consistency

**Comment by ashenden** [comment]
@nLight apologies. I misspoke. I've been working on changes like this to the `dcos-ui-plugins-private` repo.

**Pull request merged**
