### PR TITLE
fix(Dropdown): ref was called without current

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Additionally this adds some safe guards, so we don't fail with missing
properties

### CODE REVIEW

**Comment by nLight** [comment]
What about this ref? https://github.com/mesosphere/reactjs-components/pull/511/files#diff-acc3a01ef84560b7b72c24ff5650dbf0R233

**Comment by DanielMSchmidt** [comment]
That one was too low to reach :D

**Comment by nLight** [comment]
@DanielMSchmidt this PR makes components 16 only, correct? Previously one wouldn't need `.current`

**Comment by DanielMSchmidt** [comment]
Yeah, that is the case. I'll make a second round to see if I missed some somewhere and change the dependency to be react >= 16

**Comment by nLight** [comment]
fails seem to be legit

**Comment by DanielMSchmidt** [comment]
Could you maybe take a look @nLight? From what I understand the references are not instanciated, but I don't really understand why

**Comment by DanielMSchmidt** [comment]
I found this error, I need to check if it's also there on master
```
raven.js:390 Uncaught TypeError: Illegal invocation
    at Select.handleDropdownChange (Select.js?9d8b:82)
    at Dropdown.handleItemClick (Dropdown.js?8e10:160)
```

**Comment by DanielMSchmidt** [comment]
So the select won't do anything, let's get this fixed 💪

**Comment by nLight** [comment]
ok, I think I nailed the last one

**Comment by DanielMSchmidt** [comment]
Nice, so merge and integrate?

**Pull request merged**
