### PR TITLE
Allow modal to enable and disable transitions

### PR DESCRIPTION
**Pull request by daiyiwhale**
New props to separately disable the modals transitions:

```
  transitionsIn: PropTypes.bool
  transitionsOut: PropTypes.bool
```

Also cleaning up unused props!

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @rcorral

**Comment by philipnrmn** [comment]
LGTM!

**Comment by jfurrow** [comment]
Chris and I chatted online and we agreed to add the ability to enable/disable `appear`, `enter`, and `leave` animation events that are supported by `CSSTransitionGroup`

**Comment by jfurrow** [comment]
Thanks @daiyiwhale, looks great!

**Pull request merged**
